esphome:
  name: test_device
  platform: ESP8266
  board: nodemcuv2
  includes:
    - AM2315asukiaaa.h
  libraries:
    - "AM2320_asukiaaa"
    
logger:
  level: verbose

i2c:
    sda: D2
    scl: D1
    scan: False

sensor:
  - platform: custom
    lambda: |-
      auto AM2315sensor = new AM2315();
      App.register_component(AM2315sensor);
      return {AM2315sensor->temperature, AM2315sensor->humidity};

    sensors:
      - name: Temperature
        unit_of_measurement: °C
        accuracy_decimals: 1
      - name: Humidity
        icon: "mdi:water-percent"
        unit_of_measurement: "%"
        accuracy_decimals: 1


